name: Deployment

on:
  push:
    branches: [multicontainers]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy with Docker Compose
      run: |
        echo "Starting Docker Compose deployment..."
        
        scp -P 2200 -o StrictHostKeyChecking=no docker-compose.yml vlad@course.prafdin.ru:/home/vlad/catty-compose/
        
        if [ -d "db" ]; then
          scp -P 2200 -o StrictHostKeyChecking=no -r db/ vlad@course.prafdin.ru:/home/vlad/catty-compose/
        fi
        
        ssh -p 2200 -o StrictHostKeyChecking=no vlad@course.prafdin.ru '
          set -e
          cd /home/vlad/catty-compose
          
          echo "Логинимся в GitHub Container Registry..."
          echo "${{ secrets.DOCKER_PAT }}" | docker login ghcr.io -u comandir26 --password-stdin
          
          echo "Проверяем docker-compose.yml..."
          cat docker-compose.yml
          
          echo "Останавливаем существующий стек..."
          docker-compose down  true
          
          echo "Запускаем новый стек с Docker Compose..."
          docker-compose up -d
          
          echo "Ждем запуска сервисов..."
          sleep 30
          
          echo "Проверяем статус сервисов..."
          docker-compose ps
          
          echo "Проверяем здоровье приложения..."
          curl -f http://localhost:8181 && echo "Приложение работает"  echo "Проверка здоровья не удалась"
          
          echo "Деплой завершен!"
          echo "риложение доступно по: https://app.volkovvs.course.prafdin.ru"
        '